// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "footer" section.

import React from 'react';
import FooterBasic from '@/components/sections/footer/FooterBasic';

export default function FooterSection(): React.JSX.Element {
  return (
    <div id="footer" data-section="footer">
            <FooterBasic
                columns={[
                  { title: "Hizmetler", items: [{ label: "Çimento Satışı", href: "#" }, { label: "İnşaat Malzemeleri", href: "#" }, { label: "Şantiye Tedariki", href: "#" }] },
                  { title: "İletişim", items: [{ label: "Gazi Osman Paşa, Bursa Yolu, 77100 Yalova Merkez/Yalova", href: "#" }, { label: "selcukinsaatmalzemeleri@gmail.com", href: "mailto:selcukinsaatmalzemeleri@gmail.com" }, { label: "+90 542 744 42 77", href: "tel:+90000000000" }]}
                ]}
                leftText="© 2026 Selçuk Ticaret Beton & Çimento. Tüm Hakları Saklıdır."
                rightText="Gizlilik Politikası"
            />
          </div>
  );
}
