// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "iletisim" section.

import React from 'react';
import ContactCta from '@/components/sections/contact/ContactCta';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function IletisimSection(): React.JSX.Element {
  return (
    <div id="iletisim" data-section="iletisim">
            <SectionErrorBoundary name="iletisim">
              <ContactCta
                tag="Bize Ulaşın"
                text="İhtiyaçlarınız için profesyonel çözümler sunuyoruz. Hemen iletişime geçin."
                primaryButton={{ text: "WhatsApp'tan Yaz", href: "https://wa.me/905427444277" }}
                secondaryButton={{ text: "Hemen Ara", href: "tel:+902268143993" }}
                textAnimation="slide-up"
              />
            </SectionErrorBoundary>
          </div>
  );
}
