// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "kurumsal-foto" section.

import React from 'react';
import AboutFeaturesSplit from '@/components/sections/about/AboutFeaturesSplit';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function KurumsalFotoSection(): React.JSX.Element {
  return (
    <div id="kurumsal-foto" data-section="kurumsal-foto">
            <SectionErrorBoundary name="kurumsal-foto">
              <AboutFeaturesSplit
                tag="Selçuk Ticaret"
                title="Yılların Tecrübesiyle Güvenilir Hizmet"
                description="Selçuk Ticaret olarak Yalova ve çevresinde kaliteli ürün, güvenilir hizmet ve zamanında teslimat anlayışıyla müşterilerimize hizmet veriyoruz."
                items={[]}
                imageSrc="https://storage.googleapis.com/webild/users/user_3FoznR22VUsYjNYraGEuDHkeUVM/uploaded-1784406467541-z1vh6uhx.jpg"
                textAnimation="slide-up"
              />
            </SectionErrorBoundary>
          </div>
  );
}
