// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "metrics" section.

import React from 'react';
import MetricsFeatureCards from '@/components/sections/metrics/MetricsFeatureCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function MetricsSection(): React.JSX.Element {
  return (
    <div id="metrics" data-section="metrics">
            <SectionErrorBoundary name="metrics">
              <MetricsFeatureCards
                tag="Başarılarımız"
                title="Güvenle Büyüyoruz"
                description="Yılların birikimi ve binlerce teslimat."
                metrics={[
                  { value: "34+", title: "Yıllık Deneyim", features: ["Tecrübeli uzman kadro", "Sektör bilgisi"] },
                  { value: "1000+", title: "Mutlu Müşteri", features: ["Sadık iş ortakları", "Referanslı projeler"] },
                  { value: "5000+", title: "Teslimat", features: ["Zamanında sevkiyat", "Güvenli lojistik"] },
                  { value: "100%", title: "Müşteri Memnuniyeti", features: ["Hızlı destek", "Kalite odaklı"] }
                ]}
                textAnimation="slide-up"
              />
            </SectionErrorBoundary>
          </div>
  );
}
