// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "neden-biz" section.

import React from 'react';
import FeaturesRevealCards from '@/components/sections/features/FeaturesRevealCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function NedenBizSection(): React.JSX.Element {
  return (
    <div id="neden-biz" data-section="neden-biz">
            <SectionErrorBoundary name="neden-biz">
              <FeaturesRevealCards
                tag="Neden Selçuk Ticaret?"
                title="İnşaat Projelerinizin Temel Taşı"
                description="Bizi tercih etmeniz için temel nedenler."
                items={[
                  { title: "Kaliteli Ürün", description: "Standartlara uygun, en yüksek kaliteli malzemeler.", imageSrc: "http://img.b2bpic.net/free-photo/man-room-with-solid-fuel-boiler-working-biofuel-economical-heating_169016-14582.jpg" },
                  { title: "Güvenilir Hizmet", description: "Söz verdiğimiz zamanda ve kalitede teslimat.", imageSrc: "http://img.b2bpic.net/free-photo/side-view-plus-size-people-working-construction_23-2150772854.jpg" },
                  { title: "Hızlı Teslimat", description: "Geniş araç filomuzla hızlı sevkiyat.", imageSrc: "http://img.b2bpic.net/free-photo/focused-ceo-formal-suit-hardhat-standing-warehouse-talking-mobile-phone_74855-16370.jpg" },
                  { title: "Uygun Fiyat", description: "Rekabetçi fiyat politikasıyla bütçe dostu.", imageSrc: "http://img.b2bpic.net/free-photo/people-taking-care-warehouse-logistics-together_23-2149128297.jpg" },
                  { title: "Deneyimli Ekip", description: "Profesyonel kadromuzla teknik destek.", imageSrc: "http://img.b2bpic.net/free-photo/medium-shot-people-working-construction_23-2150772880.jpg" }
                ]}
                textAnimation="slide-up"
              />
            </SectionErrorBoundary>
          </div>
  );
}
