// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "surec" section.

import React from 'react';
import FeaturesRevealCards from '@/components/sections/features/FeaturesRevealCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function SurecSection(): React.JSX.Element {
  return (
    <div id="surec" data-section="surec">
            <SectionErrorBoundary name="surec">
              <FeaturesRevealCards
                tag="Nasıl Çalışıyoruz?"
                title="4 Adımda Teslimat"
                description="Süreci hızlandırarak inşaatınızı durdurmuyoruz."
                items={[
                  { title: "Talebinizi Alıyoruz", description: "İhtiyaçlarınızı uzman ekibimize iletin.", imageSrc: "http://img.b2bpic.net/free-photo/colleagues-smiling-speaking-holding-tablet-notebook-office_176420-935.jpg" },
                  { title: "Teklif Hazırlıyoruz", description: "En uygun fiyat seçenekleriyle.", imageSrc: "http://img.b2bpic.net/free-photo/business-owner-working-their-strategy_23-2149241314.jpg" },
                  { title: "Ürünleri Hazırlıyoruz", description: "Kalite kontrol süreçlerimizle.", imageSrc: "http://img.b2bpic.net/free-photo/happy-employee-dancing-warehouse_482257-81048.jpg" },
                  { title: "Hızlı Teslim Ediyoruz", description: "Sahada hızlı ve güvenli teslimat.", imageSrc: "http://img.b2bpic.net/free-photo/transport-logistics-concept_23-2151541898.jpg" }
                ]}
                textAnimation="slide-up"
              />
            </SectionErrorBoundary>
          </div>
  );
}
