// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "testimonials" section.

import React from 'react';
import TestimonialMarqueeCards from '@/components/sections/testimonial/TestimonialMarqueeCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function TestimonialsSection(): React.JSX.Element {
  return (
    <div id="testimonials" data-section="testimonials">
            <SectionErrorBoundary name="testimonials">
              <TestimonialMarqueeCards
                tag="Müşteri Yorumları"
                title="Bizi Müşterilerimize Sorun"
                description="Müşterilerimizin memnuniyeti en büyük motivasyonumuz."
                testimonials={[
                  { name: "Ahmet Yılmaz", role: "Müteahhit", quote: "Yıllardır Selçuk Ticaret ile çalışıyoruz, çok profesyoneller.", imageSrc: "http://img.b2bpic.net/free-photo/mature-manager-communicating-with-female-distribution-warehouse-worker-industrial-building_637285-4899.jpg" },
                  { name: "Ayşe Kaya", role: "Mimari Tasarım", quote: "İhtiyaçlarımıza tam zamanında cevap veriyorlar, teşekkürler.", imageSrc: "http://img.b2bpic.net/free-photo/architect-her-working-desk-with-blueprints-front-her-working-new-projects-architecture-design_482257-33166.jpg" },
                  { name: "Mehmet Demir", role: "Şantiye Şefi", quote: "Malzeme kaliteleri ve hızları tartışılmaz, mükemmel.", imageSrc: "http://img.b2bpic.net/free-photo/engineer-oversees-assembly-tools-tablet-industry-plant-surrounded-by-metal-steel-machinery_482257-135546.jpg" },
                  { name: "Zeynep Arslan", role: "İnşaat Mühendisi", quote: "Projemizin en büyük destekçisi, çözüm ortağımızdır.", imageSrc: "http://img.b2bpic.net/free-photo/female-engineer-helmet-gear-holding-construction-plan-pointing-it_114579-24439.jpg" },
                  { name: "Canan Çelik", role: "Firma Sahibi", quote: "Güler yüzlü ve uzman ekiple çalışmak çok keyifli.", imageSrc: "http://img.b2bpic.net/free-photo/my-big-dream-is-working-big-company_329181-11421.jpg" }
                ]}
                textAnimation="slide-up"
              />
            </SectionErrorBoundary>
          </div>
  );
}
