// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "urunler" section.

import React from 'react';
import FeaturesImageBento from '@/components/sections/features/FeaturesImageBento';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function UrunlerSection(): React.JSX.Element {
  return (
    <div id="urunler" data-section="urunler">
            <SectionErrorBoundary name="urunler">
              <FeaturesImageBento
                tag="Ürünlerimiz"
                title="Geniş Ürün Yelpazesi"
                description="İnşaatınızın ihtiyacı olan her şey burada."
                items={[
                  { title: "İnşaat Demiri", description: "Dayanıklı ve sertifikalı.", imageSrc: "https://storage.googleapis.com/webild/users/user_3FoznR22VUsYjNYraGEuDHkeUVM/uploaded-1784409071485-54aga8sx.jpg" },
                  { title: "Çimento", description: "Endüstriyel standartlarda.", imageSrc: "https://storage.googleapis.com/webild/users/user_3FoznR22VUsYjNYraGEuDHkeUVM/uploaded-1784409082483-cr0h7fie.jpg" },
                  { title: "Beyaz Çimento", description: "Dekoratif ve sağlam.", imageSrc: "https://storage.googleapis.com/webild/users/user_3FoznR22VUsYjNYraGEuDHkeUVM/uploaded-1784409091990-adq4398j.jpg" },
                  { title: "Gazbeton", description: "Enerji tasarruflu.", imageSrc: "https://storage.googleapis.com/webild/users/user_3FoznR22VUsYjNYraGEuDHkeUVM/uploaded-1784408726491-7ipe9tpi.webp" },
                  { title: "Kireç", description: "Harçlarınız için ideal.", imageSrc: "https://storage.googleapis.com/webild/users/user_3FoznR22VUsYjNYraGEuDHkeUVM/uploaded-1784409102935-dgv9lt49.jpg" },
                  { title: "Tuğla", description: "Yüksek mukavemetli.", imageSrc: "https://storage.googleapis.com/webild/users/user_3FoznR22VUsYjNYraGEuDHkeUVM/uploaded-1784409112528-a3t8r8uy.webp" },
                  { title: "Kum & Mıcır", description: "Doğal ve kaliteli.", imageSrc: "https://storage.googleapis.com/webild/users/user_3FoznR22VUsYjNYraGEuDHkeUVM/uploaded-1784409129100-qdbr1qm6.jpg" }
                ]}
                textAnimation="slide-up"
              />
            </SectionErrorBoundary>
          </div>
  );
}
